pipeline {
   agent any

   tools {
      go 'go1.13'
   }

   stages {
      stage('Pull') {
          steps {
              git 'https://github.com/200106-uta-go/JKJP2.git'   
          }
      }
      stage('Build and Run') {
         steps {
            
            sh 'go build -o gg ./cmd/getgreet'
            sh 'go build -o sg ./cmd/sendgreet'
            sh './gg & ./sg'
         }

         post {
            success {
               sh "echo SUCCESS"
            }
         }
      }
   }
}